name: test
on:
  push:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: curl, dom, exif, fileinfo, hash, json, mbstring, mysqli, sodium, openssl, pcre, imagick, xml, zip
          ini-values: assert.exception=1, zend.assertions=1

      - name: Install deps
        run: composer install

      - name: test
        run: php artisan test
